# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f060826a8949899b6a3dc49e1d4dda3b80ced21c2229a3e4bd863ea6bdada4cd354567b7df67261ba2bd45618c953d185412b2832bc9176540f60ca2f28edcf1

test:
  secret_key_base: b2af3b3466e45a2f1185ab5db1f4c482cc4ece3c3f3a58eca46185a08eacc1bf41b2249bd23681c18602f46e1081a28a61ce84cf0df2e2d2973cf9b038dce50e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
